ignore:
  - CVE-2024-54133  # actionpack vulnerability - handled when we upgrade rails to 7+
  - GHSA-vfm5-rmrh-j26v  # actionpack vulnerability - handled when we upgrade rails to 7+
  - GHSA-r95h-9x8f-r3f7 # actionpack vulnerability - handled when we upgrade rails to 7+
  - GHSA-vvfq-8hwr-qm4m  # nokogiri vulnerability - handled when we upgrade rails to 7+