Time::DATE_FORMATS[:default] = '%Y-%m-%d %H:%M'
Time::DATE_FORMATS[:default_with_time_zone] = '%Y-%m-%d %H:%M %Z'
Time::DATE_FORMATS[:date] = '%Y-%m-%d'
Time::DATE_FORMATS[:metadata_dates_format] = '%Y-%m-%dT%H:%M:00.000Z'
Time::DATE_FORMATS[:echo_format] = '%A, %B %d, %Y at %l:%M %P'
Time::DATE_FORMATS[:log_time] = '%Y-%m-%d %H:%M:%S %Z'
