module SystemIdentityPermissionsHelper

  # SYSTEM_AUDIT_REPORT_PERMISSIONS = %w(read)
  # METRIC_DATA_POINT_SAMPLE_PERMISSIONS = %w(read)
  # SYSTEM_INITIALIZER_PERMISSIONS = %w(create)
  # ARCHIVE_RECORD_PERMISSIONS = %w(delete)
  # ERROR_MESSAGE_PERMISSIONS = %w(update)
  # TOKEN_PERMISSIONS = %w(read delete)
  # TOKEN_REVOCATION_PERMISSIONS = %w(create)
  # EXTENDED_SERVICE_ACTIVATION_PERMISSIONS = %w(create)
  # ORDER_AND_ORDER_ITEMS_PERMISSIONS = %w(read delete)
  # PROVIDER_PERMISSIONS = %w(create delete)
  # TAG_GROUP_PERMISSIONS = %w(create update delete)
  # TAXONOMY_PERMISSIONS = %w(create)
  # TAXONOMY_ENTRY_PERMISSIONS = %w(create)
  # USER_CONTEXT_PERMISSIONS = %w(read)
  # USER_PERMISSIONS = %w(read update delete)
  # GROUP_PERMISSIONS = %w(create read)
  # ANY_ACL_PERMISSIONS = %w(create read update delete)
  # EVENT_NOTIFICATION_PERMISSIONS = %w(delete)
  # EXTENDED_SERVICE_PERMISSIONS = %w(delete)
  # SYSTEM_OPTION_DEFINITION_PERMISSIONS = %w(create delete)
  # SYSTEM_OPTION_DEFINITION_DEPRECATION_PERMISSIONS = %w(create)
  # INGEST_MANAGEMENT_ACL_PERMISSIONS = %w(read update)
  # SYSTEM_CALENDAR_EVENT_PERMISSIONS = %w(create update delete)

  SYSTEM_AUDIT_REPORT_PERMISSIONS = %w(read)
  METRIC_DATA_POINT_SAMPLE_PERMISSIONS = %w(read)
  SYSTEM_INITIALIZER_PERMISSIONS = %w(create)
  ARCHIVE_RECORD_PERMISSIONS = %w(delete)
  ERROR_MESSAGE_PERMISSIONS = %w(update)
  TOKEN_PERMISSIONS = %w(read delete)
  TOKEN_REVOCATION_PERMISSIONS = %w(create)
  EXTENDED_SERVICE_ACTIVATION_PERMISSIONS = %w(create)
  ORDER_AND_ORDER_ITEMS_PERMISSIONS = %w(read delete)
  PROVIDER_PERMISSIONS = %w(create delete)
  TAG_GROUP_PERMISSIONS = %w(create update delete)
  TAXONOMY_PERMISSIONS = %w(create)
  TAXONOMY_ENTRY_PERMISSIONS = %w(create)
  USER_CONTEXT_PERMISSIONS = %w(read)
  USER_PERMISSIONS = %w(read update delete)
  GROUP_PERMISSIONS = %w(create read)
  ANY_ACL_PERMISSIONS = %w(create read update delete)
  EVENT_NOTIFICATION_PERMISSIONS = %w(delete)
  EXTENDED_SERVICE_PERMISSIONS = %w(delete)
  SYSTEM_OPTION_DEFINITION_PERMISSIONS = %w(create delete)
  SYSTEM_OPTION_DEFINITION_DEPRECATION_PERMISSIONS = %w(create)
  INGEST_MANAGEMENT_ACL_PERMISSIONS = %w(read update)
  SYSTEM_CALENDAR_EVENT_PERMISSIONS = %w(create update delete)

  SYSTEM_TARGETS = %w(
    ANY_ACL
    ARCHIVE_RECORD
    ERROR_MESSAGE
    EVENT_NOTIFICATION
    EXTENDED_SERVICE
    EXTENDED_SERVICE_ACTIVATION
    GROUP
    INGEST_MANAGEMENT_ACL
    METRIC_DATA_POINT_SAMPLE
    ORDER_AND_ORDER_ITEMS
    PROVIDER
    SYSTEM_AUDIT_REPORT
    SYSTEM_CALENDAR_EVENT
    SYSTEM_INITIALIZER
    SYSTEM_OPTION_DEFINITION
    SYSTEM_OPTION_DEFINITION_DEPRECATION
    TAG_GROUP
    TAXONOMY
    TAXONOMY_ENTRY
    TOKEN
    TOKEN_REVOCATION
    USER
    USER_CONTEXT
  )

  PermissionsOptions = %w(create read update delete)

end
