import React, { useState } from 'react'
import PropTypes from 'prop-types'
import ListGroup from 'react-bootstrap/ListGroup'
import { get, kebabCase } from 'lodash'
import { useNavigate, useParams } from 'react-router'
import classNames from 'classnames'

import NavigationItemError from '../NavigationItemError/NavigationItemError'
import For from '../For/For'

import prefixProperty from '../../utils/prefixProperty'
import createPath from '../../utils/createPath'

import './NavigationItem.scss'

/**
 * @typedef {Object} NavigationItem
 * @property {Object} draft Draft metadata.
 * @property {Object} section A single form section configuration.
 * @property {Object[]} validationErrors List of validation errors generated by the RJSF validator.
 * @property {String[]} visitedFields List of fields that have been visisted by the user.
 * @property {Function} setFocusField A callback function to set a field as focused.
 */

/**
 * Renders a NavigationItem
 * @param {NavigationItem} props
 *
 * @component
 * @example <caption>Render a NavigationItem</caption>
 * return (
 *   <NavigationItem />
 * )
 */
const NavigationItem = ({
  draft,
  section,
  validationErrors,
  visitedFields,
  setFocusField
}) => {
  const [hasFocus, setHasFocus] = useState(false)
  const {
    conceptId,
    sectionName
  } = useParams()
  const navigate = useNavigate()

  const { displayName } = section

  const isSectionDisplayed = kebabCase(displayName) === sectionName

  // Does the form section have values
  const hasValues = section.properties.some((propertyPrefix) => {
    const value = draft[propertyPrefix]

    return value !== undefined
  })

  // `hasErrors` is used if any errors exist on the form section, so it loops over all validationErrors
  const hasErrors = validationErrors.some((error) => {
    const { property } = error

    return section.properties.some((propertyPrefix) => prefixProperty(property).startsWith(`${prefixProperty(propertyPrefix)}`))
  })

  const errorsWithGroups = {}
  const errorsWithoutGroups = []

  // Multiple errors can occur within a nested field or array field, so we group those errors together
  // in order to display them together within NavigationItemError
  validationErrors.forEach((validationError) => {
    const { property } = validationError
    const visited = visitedFields.includes(prefixProperty(property))

    // Nested/Array errors from sjv start with `.`
    const isGrouped = property.startsWith('.')

    // If the error is part of a group, build the group to store in `errorsWithGroups`
    if (isGrouped) {
      const path = createPath(property)
      const regexp = /^(.*[^\\[]+)\[(\d+)\]/
      const match = path.match(regexp)

      let fieldName
      // If `match[1]` exists the regex found an array index
      if (match && match[1]) {
        // This is an array field
        [, fieldName] = match[1].split('.')
        const arrayIndex = parseInt(match[2], 10)

        // Find the total number of values for this array in the draft metadata
        const matchedPath = match[1].substring(1)
        const results = get(draft, matchedPath)

        // If no results exist, default the length parameter to 1
        const length = Math.max(results?.length || 1, arrayIndex + 1)

        // Build a field name with the `arrayIndex` and `length` values: "RelatedURLs (1 of 2)"
        fieldName = `${fieldName} (${arrayIndex + 1} of ${length})`
      } else {
        // This is an object
        const parts = property.split('.');
        [, fieldName] = parts
      }

      // Create a new array of errors for this `fieldName` if it doesn't exist
      errorsWithGroups[fieldName] ||= []

      // Add the new error the the list
      errorsWithGroups[fieldName] = [
        ...errorsWithGroups[fieldName],
        {
          ...validationError,
          visited
        }
      ]
    } else {
      // If the error was not nested, save it in `errorsWithoutGroups`
      errorsWithoutGroups.push({
        ...validationError,
        visited
      })
    }
  })

  // Combine the errors without groups to those with groups
  const errors = [
    ...errorsWithoutGroups,
    ...Object.keys(errorsWithGroups).map((fieldName) => ({
      fieldName,
      errors: errorsWithGroups[fieldName]
    }))
  ]

  return (
    <div key={displayName}>
      <ListGroup.Item
        className={
          classNames([
            'navigation-item__item d-flex px-1 py-1 border-0',
            {
              'navigation-item__item--isFocused': hasFocus
            },
            {
              'navigation-item__item--isActive': isSectionDisplayed
            }
          ])
        }
        action
        onMouseOver={
          () => {
            setHasFocus(true)
          }
        }
        onMouseOut={
          () => {
            setHasFocus(false)
          }
        }
        onClick={
          () => {
            // Navigate to the correct form
            navigate(`../${conceptId}/${kebabCase(displayName)}`)

            // Ensure the window is scrolled to the top of the page
            window.scroll(0, 0)
          }
        }
      >
        <span>
          <i
            // TODO tooltips
            role="img"
            aria-label={displayName}
            className={
              classNames([
                'eui-icon eui-icon--sm navigation-item__icon',
                {
                  'eui-fa-circle-o navigation-item__icon--not-started': !hasValues && !hasErrors
                },
                {
                  'eui-fa-times-circle navigation-item__icon--error': hasErrors && isSectionDisplayed
                },
                {
                  'eui-fa-circle-o navigation-item__icon--error': hasErrors && !isSectionDisplayed
                },
                {
                  'eui-check navigation-item__icon--pass': !hasErrors && hasValues
                }
              ])
            }
          />

          {displayName}
        </span>
      </ListGroup.Item>

      <For each={errors}>
        {
          (error) => {
            if (!isSectionDisplayed) return null

            return (
              <NavigationItemError
                key={JSON.stringify(error)}
                error={error}
                setFocusField={setFocusField}
              />
            )
          }
        }
      </For>
    </div>
  )
}

NavigationItem.defaultProps = {
  validationErrors: []
}

NavigationItem.propTypes = {
  draft: PropTypes.shape({}).isRequired,
  section: PropTypes.shape({
    displayName: PropTypes.string,
    properties: PropTypes.arrayOf(PropTypes.string)
  }).isRequired,
  validationErrors: PropTypes.arrayOf(
    PropTypes.shape({})
  ),
  visitedFields: PropTypes.arrayOf(
    PropTypes.string
  ).isRequired,
  setFocusField: PropTypes.func.isRequired
}

export default NavigationItem
